version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www
      - ./database/database.sqlite:/var/www/database/database.sqlite
    environment:
      APP_ENV: local
      APP_DEBUG: 1
      APP_KEY: base64:your-app-key-here
    command: php artisan serve --host=0.0.0.0 --port=8000
